stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package -DskipTests

deploy:
  stage: deploy
  script:
    - mvn deploy